services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - app-data:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app-data:/var/www/html:ro
    ports:
      - "8080:80"
    depends_on:
      - php

volumes:
  db-data:
  app-data:
